# Generated by Django 2.2 on 2019-06-22 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Electrical and Communication', 'Electrical and Communication')], default='Information Technology', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Contact_NO',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='Hobbies',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='Interest',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='Linkedin_URL',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
