# Generated by Django 2.2 on 2019-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190622_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Interest',
            new_name='Skills',
        ),
    ]
